//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFridgeServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalFridgeDBEntities1 : DbContext
    {
        public MedicalFridgeDBEntities1()
            : base("name=MedicalFridgeDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fridge> Fridges { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<Medicament> Medicaments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WriteOff> WriteOffs { get; set; }
    }
}
