//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFridgeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicaments
    {
        public int IdMedicament { get; set; }
        public int IdFridge { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
        public System.DateTime DataProduction { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> MinTemperature { get; set; }
        public Nullable<decimal> MaxTemperature { get; set; }
        public bool Status { get; set; }
        public string DataAddInFridge { get; set; }
    
        public virtual Fridges Fridges { get; set; }
    }
}
