//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFridgeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicament()
        {
            this.WriteOffs = new HashSet<WriteOff>();
        }
    
        public int IdMedicament { get; set; }
        public int IdFridge { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
        public System.DateTime DataProduction { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public decimal Price { get; set; }
        public string Information { get; set; }
    
        public virtual Fridge Fridge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WriteOff> WriteOffs { get; set; }
    }
}
