//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalFridgeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOff
    {
        public int IdWriteOff { get; set; }
        public int IdMedicament { get; set; }
        public System.DateTime DataWriteOff { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
    
        public virtual Medicament Medicament { get; set; }
    }
}
